server:
  port: 8080

spring:
  ai:
    mcp:
      server:
        type: sync
        webmvc:
          protocol: streamable
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: alpha-feature-engine-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

alpaca:
  api-key: ${ALPACA_API_KEY:default_key}
  api-secret: ${ALPACA_API_SECRET:default_secret}
  symbols: ${ALPACA_SYMBOLS:PLTR,QQQ,VUG,SPMO}
  ws-url: ${ALPACA_WS_URL:wss://stream.data.alpaca.markets/v2/iex}

binance:
  symbols: ${BINANCE_SYMBOLS:BTCUSDT,ETHUSDT,SOLUSDT}
  ws-url: ${BINANCE_WS_URL:wss://stream.binance.us:9443/ws}

alphavantage:
  api-key: ${ALPHAVANTAGE_API_KEY:default_key}
  symbols: ${ALPHAVANTAGE_SYMBOLS:PLTR,QQQ}
  enabled: true
